from datetime import datetime
from bson import ObjectId

class User:
    @staticmethod
    def create(name, email, password_hash, role="user"):
        return {
            "name": name,
            "email": email,
            "password_hash": password_hash,
            "role": role,
            "created_at": datetime.utcnow()
        }

class Photo:
    @staticmethod
    def create(user_id, file_path, embeddings=None, detected_faces=None):
        return {
            "user_id": ObjectId(user_id) if isinstance(user_id, str) else user_id,
            "file_path": file_path,
            "embeddings": embeddings or [],
            "detected_faces": detected_faces or [],
            "processed": False,
            "uploaded_at": datetime.utcnow()
        }

class Person:
    @staticmethod
    def create(user_id, name, face_cluster_id, representative_image_url=None):
        return {
            "user_id": ObjectId(user_id) if isinstance(user_id, str) else user_id,
            "name": name,
            "face_cluster_id": face_cluster_id, # Can be generated by clustering algo
            "representative_image_url": representative_image_url,
            "created_at": datetime.utcnow()
        }
